# Generated by Django 4.1.1 on 2022-10-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-updated", "-created"]},
        ),
    ]
