# Generated by Django 4.1.1 on 2022-10-13 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_comments_article_comments_email_comments_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comments", name="author",),
        migrations.AddField(
            model_name="comments",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
