# Generated by Django 4.1.1 on 2022-10-13 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_comments_author_comments_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="blog.post"
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="body",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
